### ISSUE TITLE
Issues to get proper state of garage door using Shelly Addon

### ISSUE THREAD

**Issue by norb-HB** [jmaferreira/homebridge-garage-door-shelly1#5]
Hi Miguel,

thank you for providing this module. This came very handy for me.

Recently I extended my Shelly1 with a magnetic sensor and the Shelly Temperatur Sensor Addon for Shelly 1/1PM. This is due to my system works with 230V. 

The state of the garage door is displayed accurately in the shelly app.
However I'd like to see the proper state in HK.

I've changed the settings of the module to:

"name": "Garagentor",
           "http_method": "GET",
           "openURL": "http://192.168.x.xxx/relay/0?turn=on",
           "closeURL": "http://192.168.x.xxx/relay/0?turn=on",
           "openTime": 17,
           "closeTime": 17,
           "autoLock": false,
           "autoLockDelay": 20,
           "polling": true,
           "pollInterval": 30,
           "statusURL": "http://192.168.x.xxxx/status",
           "statusKey": "$.ext_switch[0].input",
           "statusValueOpen": "1",
           "statusValueClosed": "0",
           "statusValueOpening": "2",
           "statusValueClosing": "3",
           "debug": true,
           "accessory": "GarageDoorOpener"  

It seems wether the status key I'm using is somehow wrong or the poll does not happen.
The debug option did not log any infos but open/close. When I additionaly switch the HB debug on HB is in an endless restart loop.

I'd would be very happy if you could help me.

Cheers
Norbert

**Comment by jmaferreira** [comment]
Hi,

Turning the debug to on should log the polling of the status... maybe i've introduced a bug in the last version.

Can you please revert to version 1.1.0 to see if it shows the log correctly and report back?

**Comment by norb-HB** [comment]
Thanks for coming back so quickly!

I've did the downgrade to 1.1.0 and the debug works now fine.
This is an sample result from open/close door:
[17.2.2021, 10:05:15] [Garagentor] Transformed status value from undefined to 0 ($.ext_switch[0].input)
[17.2.2021, 10:05:15] [Garagentor] Updated state to: 0
[17.2.2021, 10:05:45] [Garagentor] Transformed status value from undefined to 0 ($.ext_switch[0].input)
[17.2.2021, 10:05:45] [Garagentor] Updated state to: 0
[17.2.2021, 10:06:15] [Garagentor] Transformed status value from undefined to 0 ($.ext_switch[0].input)
[17.2.2021, 10:06:15] [Garagentor] Updated state to: 0

State ist always 0.

Actually the key for the external switch seems to be generally ok since is been used from someone else in the shelly forum: https://www.shelly-support.eu/forum/index.php?thread/6525-http-request-shortcuts-garagentor-zustandsanzeige-abfragen/

I don't know if you have access to the support forum. Here a few lines from there which seem to prove the right key:

const ext_switch = JSON.parse(response.body).ext_switch[0].input; 
if(ext_switch == 0){changeIcon("", "bitsies_upload");renameShortcut("", "Garage Geöffnet");
{Zustand = "Geöffnet"}; 
}
if(ext_switch == 1){changeIcon("" , "bitsies_download");renameShortcut("", "Garage Geschlossen");
{Zustand = "Geschlossen"};
}
showToast(''+Zustand+'')



When  calling http://shelly-ip/status in my browser it delivers back the proper value for ext_switch.

**Comment by jmaferreira** [comment]
Looking at the log entry, it seems that your jsonpath is not correct. The extracted value is `undefined`.

Can you post a example JSON extracted from your service?

**Comment by norb-HB** [comment]
Sorry, I'm not clear what ist meant with 'service'
The browser output?

**Comment by jmaferreira** [comment]
Yes. Just add here the response you get from the shelly

**Comment by norb-HB** [comment]
Thanks for clarifying.
  |  
-- | --
wifi_sta |  
connected | true
ssid | "MYWLAN"
ip | "192.xxx.x.xx"
rssi | -89
cloud |  
enabled | true
connected | true
mqtt |  
connected | false
time | "10:25"
unixtime | 1613553940
serial | 263
has_update | false
mac | "XXXXXXXXX"
cfg_changed_cnt | 7
actions_stats |  
skipped | 0
ext_switch |  
0 |  
input | 1
relays |  
0 |  
ison | false
has_timer | false
timer_started | 0
timer_duration | 0
timer_remaining | 0
source | "timer"
meters |  
0 |  
power | 0
is_valid | true
inputs |  
0 |  
input | 0
event | ""
event_cnt | 0
ext_sensors | {}
ext_temperature | {}
ext_humidity | {}
update |  
status | "idle"
has_update | false
new_version | "20210115-102904/v1.9.4@e2732e05"
old_version | "20210115-102904/v1.9.4@e2732e05"
beta_version | "20210209-101435/v1.10.0-rc2-g0cf9ee3-heads/v1.10.0-rc2"
ram_total | 50704
ram_free | 37796
fs_size | 233681
fs_free | 145078
uptime | 68538


I did a wget on my HB Pi to make sure that status could be read as well:

pi@homebridge:~/temp $ wget 192.xxx.x.xx/status
--2021-02-17 10:53:28--  http://192.xxx.x.xx/status
Verbindungsaufbau zu 192.xxx.x.xx:80 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 881 [application/json]
Wird in »status« gespeichert.

status                                     100%[=====================================================================================>]     881  --.-KB/s    in 0,005s  

2021-02-17 10:53:28 (174 KB/s) - »status« gespeichert [881/881]


pi@homebridge:~/temp $ cat status 
{"wifi_sta":{"connected":true,"ssid":"MyWLAN","ip":"192.xxx.x.xx","rssi":-86},"cloud":{"enabled":true,"connected":true},"mqtt":{"connected":false},"time":ime":1613555608,"serial":263,"has_update":false,"mac":"XXXXXXX","cfg_changed_cnt":7,"actions_stats":{"skipped":0},"ext_switch":{"0":{"input":1}},"relaalse,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"source":"timer"}],"meters":[{"power":0.00,"is_valid":true}],"inputs":[{"in:"","event_cnt":0}],"ext_sensors":{},"ext_temperature":{},"ext_humidity":{},"update":{"status":"idle","has_update":false,"new_version":"20210115-102904/v1."old_version":"20210115-102904/v1.9.4@e2732e05","beta_version":"20210209-101435/v1.10.0-rc2-g0cf9ee3-heads/v1.10.0-rc2"},"ram_total":50704,"ram_free":38352pi@homebridge:~/temp $

**Comment by jmaferreira** [comment]
Can you just paste a well formed version of that last part (the JSON part)?

If you do a `curl` instead of a `wget` you might get a better result.

**Comment by norb-HB** [comment]
Here we go....

pi@homebridge:~/temp $ curl -s 192.xxx.x.xx/status|jq "."
{
  "wifi_sta": {
    "connected": true,
    "ssid": "MYWLAN",
    "ip": "192.xxx.x.xx",
    "rssi": -86
  },
  "cloud": {
    "enabled": true,
    "connected": true
  },
  "mqtt": {
    "connected": false
  },
  "time": "11:30",
  "unixtime": 1613557809,
  "serial": 263,
  "has_update": false,
  "mac": "XXXXXX",
  "cfg_changed_cnt": 7,
  "actions_stats": {
    "skipped": 0
  },
  "ext_switch": {
    "0": {
      "input": 1
    }
  },
  "relays": [
    {
      "ison": false,
      "has_timer": false,
      "timer_started": 0,
      "timer_duration": 0,
      "timer_remaining": 0,
      "source": "timer"
    }
  ],
  "meters": [
    {
      "power": 0,
      "is_valid": true
    }
  ],
  "inputs": [
    {
      "input": 0,
      "event": "",
      "event_cnt": 0
    }
  ],
  "ext_sensors": {},
  "ext_temperature": {},
  "ext_humidity": {},
  "update": {
    "status": "idle",
    "has_update": false,
    "new_version": "20210115-102904/v1.9.4@e2732e05",
    "old_version": "20210115-102904/v1.9.4@e2732e05",
    "beta_version": "20210209-101435/v1.10.0-rc2-g0cf9ee3-heads/v1.10.0-rc2"
  },
  "ram_total": 50704,
  "ram_free": 38420,
  "fs_size": 233681,
  "fs_free": 145078,
  "uptime": 72407
}

**Comment by jmaferreira** [comment]
```json
{
  "wifi_sta": {
    "connected": true,
    "ssid": "MYWLAN",
    "ip": "192.xxx.x.xx",
    "rssi": -86
  },
  "cloud": {
    "enabled": true,
    "connected": true
  },
  "mqtt": {
    "connected": false
  },
  "time": "11:30",
  "unixtime": 1613557809,
  "serial": 263,
  "has_update": false,
  "mac": "XXXXXX",
  "cfg_changed_cnt": 7,
  "actions_stats": {
    "skipped": 0
  },
  "ext_switch": {
    "0": {
      "input": 1
    }
  },
  "relays": [
    {
      "ison": false,
      "has_timer": false,
      "timer_started": 0,
      "timer_duration": 0,
      "timer_remaining": 0,
      "source": "timer"
    }
  ],
  "meters": [
    {
      "power": 0,
      "is_valid": true
    }
  ],
  "inputs": [
    {
      "input": 0,
      "event": "",
      "event_cnt": 0
    }
  ],
  "ext_sensors": {},
  "ext_temperature": {},
  "ext_humidity": {},
  "update": {
    "status": "idle",
    "has_update": false,
    "new_version": "20210115-102904/v1.9.4@e2732e05",
    "old_version": "20210115-102904/v1.9.4@e2732e05",
    "beta_version": "20210209-101435/v1.10.0-rc2-g0cf9ee3-heads/v1.10.0-rc2"
  },
  "ram_total": 50704,
  "ram_free": 38420,
  "fs_size": 233681,
  "fs_free": 145078,
  "uptime": 72407
}

```

**Comment by jmaferreira** [comment]
Your jsonpath should work fine. Try changing it to `$.ext_switch.[0].input` just to test it. Your `ext_switch`  property is not really an array.

![image](https://user-images.githubusercontent.com/3181302/108192782-98adb800-710c-11eb-8b29-ab3cc8ac0d80.png)

**Comment by norb-HB** [comment]
did so 

This resulted in an infite restart cycle and I had to stop the HB service.

Msg in HB Log is:

[17.2.2021, 12:20:06] Error: Parse error on line 1:
$.ext_switch.[0].input
-------------^
Expecting 'STAR', 'IDENTIFIER', 'SCRIPT_EXPRESSION', 'INTEGER', 'END', got '['
    at Parser.parseError (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/jsonpath/generated/parser.js:166:15)
    at Parser.parser.yy.parseError (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/jsonpath/lib/parser.js:13:17)
    at Parser.parse (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/jsonpath/generated/parser.js:224:22)
    at JSONPath.nodes (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/jsonpath/lib/index.js:118:26)
    at JSONPath.query (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/jsonpath/lib/index.js:94:22)
    at GarageDoorOpener.<anonymous> (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/index.js:105:16)
    at Request._callback (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/index.js:80:9)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-garage-door-shelly1/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

[17.2.2021, 12:20:06] Got SIGTERM, shutting down Homebridge...

**Comment by norb-HB** [comment]
I finally found the right key -> $.ext_switch.0.input

<img width="1038" alt="Bildschirmfoto 2021-02-17 um 14 31 47" src="https://user-images.githubusercontent.com/77831623/108211548-1681bb80-712d-11eb-9b61-39e7010f3f2e.png">

Thanks a lot for your help!

**Comment by jmaferreira** [comment]
Cheers. all the best.

**Comment by jmaferreira** [comment]
Meanwhile I'll try to fix the bug on the latest version.
